name: Evidently Drift Monitoring

on:
  schedule:
    - cron: "0 13 * * *"      # nightly 09:00 ET
  workflow_dispatch:          # <-- lets you run it manually now
  # optional while testing:
  # push:
  #   branches: [ main ]

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Pin to the version you successfully used locally
          pip install evidently==0.4.40 pandas scikit-learn matplotlib plotly
          # If you also have a repo requirements file, install it too (won’t fail if missing)
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Ensure we always have enough "current" rows so the monitor doesn't skip
      - name: Generate/append predictions (current rows)
        run: |
          python scripts/create_prediction.py --n-rows 120 --mode append

      - name: Run Evidently monitoring
        run: |
          python -m scripts.monitor_evidently \
            --log-csv logs/predictions.csv \
            --out-dir reports/monitoring \
            --reference-is-recent \
            --min-rows 50

      - name: Upload Evidently report
        uses: actions/upload-artifact@v4
        with:
          name: evidently-report
          path: reports/monitoring/
